apiVersion: v1
kind: Service
metadata:
  name: msaccount
  namespace: sit
  labels:
    app: msaccount
spec:
  selector:
    app: msaccount
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8999